#!/usr/bin/env bash
# This WILL overwrite the devlog.txt file!
# Run on demand rather than on every commit.
# A git hook could be more useful for version control purposes.
set -euo pipefail

DEVLOG="$(git rev-parse --show-toplevel)/devlog.txt"
git log --date=short --pretty="%ad%x09%cn%n%B%n==========%n" | \
    sed -e 's/gnewman00/Gabi Newman/g' > "$DEVLOG"

